name: Build and deploy Node.js app to Azure Web App - webappthread

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: npm install and build
        run: |
          cd threading-machine
          npm install
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./threading-machine/.next/standalone/threading-machine

      - name: Upload static files artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-static
          path: ./threading-machine/.next/static

      - name: Upload public files artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-public
          path: ./threading-machine/public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Download static files
        uses: actions/download-artifact@v4
        with:
          name: node-static
          path: ./.next/static

      - name: Download public files
        uses: actions/download-artifact@v4
        with:
          name: node-public
          path: ./public
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1D2AAE8931EC4775B5F6D214B1059CDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7B26234C82154BC680422B7141193F72 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_773A6668D9B24F5A8205CCA81F754588 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webappthread'
          slot-name: 'Production'
          package: .
          startup-command: 'node server.js'
          app-settings-json: '[{"name":"SCM_DO_BUILD_DURING_DEPLOYMENT","value":"false"},{"name":"WEBSITE_NODE_DEFAULT_VERSION","value":"~22"}]'
